### ISSUE TITLE
Example app crashes when I press a print button.

### ISSUE THREAD

**Issue by markhorrocks** [thon-ju/bluetooth_print#123]
The example app crashes when I press a press a print button. Here is the output for a couple of attempts.

```
D/BluetoothPrintPlugin( 8227): start scan 
D/BluetoothAdapter( 8227): isLeEnabled(): ON
D/BluetoothLeScanner( 8227): onScannerRegistered() - status=0 scannerId=8 mScannerId=0
V/PhoneWindow( 8227): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@45e4ab5, this = DecorView@3e7254a[MainActivity]
I/flutter ( 8227): ******************* cur device status: 12
The Flutter DevTools debugger and profiler on Lenovo TB X606F is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:42041/TZJr-0vJoFI=/
D/BluetoothAdapter( 8227): isLeEnabled(): ON
W/BluetoothAdapter( 8227): getBluetoothService() called with no BluetoothManagerCallback
D/BluetoothPrintPlugin( 8227): stateStreamHandler, current action: android.bluetooth.device.action.ACL_CONNECTED
I/flutter ( 8227): ******************* cur device status: 1
E/DeviceConnFactoryManager( 8227): ******************* wait read 
D/BluetoothSocket( 8227): close() this: android.bluetooth.BluetoothSocket@d318d76, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@6775f77, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@cf417e4mSocket: android.net.LocalSocket@18dd44d impl:android.net.LocalSocketImpl@a10b02 fd:java.io.FileDescriptor@b787c13, mSocketState: CONNECTED
D/BluetoothSocket( 8227): close() this: android.bluetooth.BluetoothSocket@d318d76, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@6775f77, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@cf417e4mSocket: null, mSocketState: CLOSED
W/System.err( 8227): java.io.IOException: bt socket closed, read return: -1
D/BluetoothSocket( 8227): close() this: android.bluetooth.BluetoothSocket@d318d76, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@6775f77, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@cf417e4mSocket: null, mSocketState: CLOSED
W/System.err( 8227):    at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:564)
W/System.err( 8227):    at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:88)
W/System.err( 8227):    at java.io.InputStream.read(InputStream.java:101)
W/System.err( 8227):    at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err( 8227):    at com.example.bluetooth_print.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:308)
W/System.err( 8227):    at com.example.bluetooth_print.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:387)
E/BluetoothPort( 8227): connection device is lost
E/DeviceConnFactoryManager( 8227): ******************* close Port macAddress -> B8:50:44:04:2A:2D
E/DeviceConnFactoryManager( 8227): ******************* read 0
D/BluetoothPrintPlugin( 8227): stateStreamHandler, current action: android.bluetooth.device.action.ACL_DISCONNECTED
I/flutter ( 8227): ******************* cur device status: 0
W/BluetoothAdapter( 8227): getBluetoothService() called with no BluetoothManagerCallback
D/BluetoothPrintPlugin( 8227): stateStreamHandler, current action: android.bluetooth.device.action.ACL_CONNECTED
I/flutter ( 8227): ******************* cur device status: 1
E/DeviceConnFactoryManager( 8227): ******************* wait read 
D/BluetoothSocket( 8227): close() this: android.bluetooth.BluetoothSocket@930f85a, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@5215a8b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@b4c1768mSocket: android.net.LocalSocket@f7d781 impl:android.net.LocalSocketImpl@bf64026 fd:java.io.FileDescriptor@2c91467, mSocketState: CONNECTED
W/System.err( 8227): java.io.IOException: bt socket closed, read return: -1
W/System.err( 8227):    at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:564)
W/System.err( 8227):    at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:88)
W/System.err( 8227):    at java.io.InputStream.read(InputStream.java:101)
W/System.err( 8227):    at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
D/BluetoothSocket( 8227): close() this: android.bluetooth.BluetoothSocket@930f85a, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@5215a8b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@b4c1768mSocket: null, mSocketState: CLOSED
W/System.err( 8227):    at com.example.bluetooth_print.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:308)
D/BluetoothSocket( 8227): close() this: android.bluetooth.BluetoothSocket@930f85a, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@5215a8b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@b4c1768mSocket: null, mSocketState: CLOSED
W/System.err( 8227):    at com.example.bluetooth_print.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:387)
E/BluetoothPort( 8227): connection device is lost
E/DeviceConnFactoryManager( 8227): ******************* close Port macAddress -> B8:50:44:04:2A:2D
E/DeviceConnFactoryManager( 8227): ******************* read 0
D/BluetoothPrintPlugin( 8227): stateStreamHandler, current action: android.bluetooth.device.action.ACL_DISCONNECTED
I/flutter ( 8227): ******************* cur device status: 0
```

**Comment by Moomak** [comment]
me too

W/BluetoothAdapter(19627): getBluetoothService() called with no BluetoothManagerCallback
D/BluetoothPrintPlugin(19627): stateStreamHandler, current action: android.bluetooth.device.action.ACL_CONNECTED
I/flutter (19627): ******************* cur device status: 1
D/ViewRootImpl[MainActivity](19627): processMotionEvent MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=477.0, y[0]=1243.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1594423, downTime=1594423, deviceId=3, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity](19627): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=477.0, y[0]=1243.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1594423, downTime=1594423, deviceId=3, source=0x1002, displayId=0 }
E/DeviceConnFactoryManager(19627): ******************* wait read 
D/ViewRootImpl[MainActivity](19627): processMotionEvent MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=477.0, y[0]=1243.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1594523, downTime=1594423, deviceId=3, source=0x1002, displayId=0 }
D/ViewRootImpl[MainActivity](19627): dispatchPointerEvent handled=true, event=MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=477.0, y[0]=1243.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1594523, downTime=1594423, deviceId=3, source=0x1002, displayId=0 }
D/BluetoothAdapter(19627): isLeEnabled(): ON
D/BluetoothSocket(19627): close() this: android.bluetooth.BluetoothSocket@2fde0cb, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@898c0a8, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@dad67c1mSocket: android.net.LocalSocket@8b82b66 impl:android.net.LocalSocketImpl@a87bea7 fd:java.io.FileDescriptor@40d3f54, mSocketState: CONNECTED
W/System.err(19627): java.io.IOException: bt socket closed, read return: -1
W/System.err(19627): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:550)
W/System.err(19627): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:88)
W/System.err(19627): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err(19627): 	at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err(19627): 	at com.example.bluetooth_print.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:308)
D/BluetoothSocket(19627): close() this: android.bluetooth.BluetoothSocket@2fde0cb, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@898c0a8, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@dad67c1mSocket: null, mSocketState: CLOSED
W/System.err(19627): 	at com.example.bluetooth_print.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:387)
E/BluetoothPort(19627): connection device is lost
D/BluetoothSocket(19627): close() this: android.bluetooth.BluetoothSocket@2fde0cb, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@898c0a8, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@dad67c1mSocket: null, mSocketState: CLOSED
D/BluetoothSocket(19627): close() this: android.bluetooth.BluetoothSocket@2fde0cb, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@898c0a8, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@dad67c1mSocket: null, mSocketState: CLOSED
E/DeviceConnFactoryManager(19627): ******************* close Port macAddress -> DD:0D:30:16:67:C8
E/DeviceConnFactoryManager(19627): ******************* read 0
D/BluetoothPrintPlugin(19627): stateStreamHandler, current action: android.bluetooth.device.action.ACL_DISCONNECTED
I/flutter (19627): ******************* cur device status: 0
