### ISSUE TITLE
cannot connect printer

### ISSUE THREAD

**Issue by zzy080615** [thon-ju/bluetooth_print#142]
DEMO has same problem

D/BluetoothAdapter(21461): cancelDiscovery(): called by: com.example.bluetooth_print_example
W/System.err(21461): java.io.IOException: read failed, socket might closed or timeout, read ret: -1
W/System.err(21461):    at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:776)
W/System.err(21461):    at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:790)
W/System.err(21461):    at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:415)
W/System.err(21461):    at com.gprinter.io.BluetoothPort.openPort(BluetoothPort.java:58)
W/System.err(21461):    at com.example.bluetooth_print.DeviceConnFactoryManager.openPort(DeviceConnFactoryManager.java:150)
W/System.err(21461):    at com.example.bluetooth_print.BluetoothPrintPlugin$3.run(BluetoothPrintPlugin.java:346)
W/System.err(21461):    at com.example.bluetooth_print.ThreadPool$1.run(ThreadPool.java:78)
W/System.err(21461):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(21461):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(21461):    at java.lang.Thread.run(Thread.java:920)
V/AutofillManager(21461): requestHideFillUi(null): anchor = null
D/BluetoothAdapter(21461): cancelDiscovery(): called by: com.example.bluetooth_print_example
W/System.err(21461): java.io.IOException: read failed, socket might closed or timeout, read ret: -1
W/System.err(21461):    at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:776)
W/System.err(21461):    at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:790)
W/System.err(21461):    at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:415)
W/System.err(21461):    at com.gprinter.io.BluetoothPort.openPort(BluetoothPort.java:58)
W/System.err(21461):    at com.example.bluetooth_print.DeviceConnFactoryManager.openPort(DeviceConnFactoryManager.java:150)
W/System.err(21461):    at com.example.bluetooth_print.BluetoothPrintPlugin$3.run(BluetoothPrintPlugin.java:346)
W/System.err(21461):    at com.example.bluetooth_print.ThreadPool$1.run(ThreadPool.java:78)
W/System.err(21461):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(21461):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(21461):    at java.lang.Thread.run(Thread.java:920)

**Comment by biloo-dev** [comment]
Is there any update on this issue?
I have the same problem with the pin code?? 
Please let us know if it has been resolved. Thanks!
