### ISSUE TITLE
Can't print after selecting the printer

### ISSUE THREAD

**Issue by jsy11** [thon-ju/bluetooth_print#192]
Hello,

We were able to make the bluetooth label printer on the list. However, upon selecting the printer nothing happens.

Can you advise how  we can make it print on connected bluetooth label printer?

Thanks so much for your help in advance, 

![7863D6CE-CCE1-4719-B804-ED9F1EFF64B6](https://github.com/thon-ju/bluetooth_print/assets/18429012/51d4e3bc-b267-4e74-8f5c-f3e4e63f88a4)

**Comment by TareqFl** [comment]
2
D/BluetoothSocket( 6613): close() this: XX:XX:XX:XX:07:97, channel: 1, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@7ebaab1, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@33fcb96, mSocket: null, mSocketState: CLOSED
E/DeviceConnFactoryManager( 6613): ******************* close Port macAddress -> 86:67:7A:00:07:97
I/BluetoothAdapter( 6613): cancelDiscovery
I/BluetoothSocket( 6613): connect() for device XX:XX:XX:XX:07:97 called by pid: 6613
W/System.err( 6613): java.io.IOException: bt socket closed, read return: -1
W/System.err( 6613): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:797)
W/System.err( 6613): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:91)
W/System.err( 6613): 	at java.io.InputStream.read(InputStream.java:218)
W/System.err( 6613): 	at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err( 6613): 	at com.example.bluetooth_print.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:308)
W/System.err( 6613): 	at com.example.bluetooth_print.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:387)
E/BluetoothPort( 6613): connection device is lost
E/DeviceConnFactoryManager( 6613): ******************* read 0
E/DeviceConnFactoryManager( 6613): ******************* wait read 
E/BluetoothPort( 6613): read length1
E/DeviceConnFactoryManager( 6613): ******************* read 1
E/DeviceConnFactoryManager( 6613): ******************* wait read 


i keep on geting wait read , im using a bluetooth thermal printer that support reciept and label printing

**Comment by amoLink** [comment]
> Hello,
> 
> We were able to make the bluetooth label printer on the list. However, upon selecting the printer nothing happens.
> 
> Can you advise how we can make it print on connected bluetooth label printer?
> 
> Thanks so much for your help in advance,
> 
> ![7863D6CE-CCE1-4719-B804-ED9F1EFF64B6](https://private-user-images.githubusercontent.com/18429012/326692375-51d4e3bc-b267-4e74-8f5c-f3e4e63f88a4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjUxNTAsIm5iZiI6MTcxNTIyNDg1MCwicGF0aCI6Ii8xODQyOTAxMi8zMjY2OTIzNzUtNTFkNGUzYmMtYjI2Ny00ZTc0LThmNWMtZjNlNGU2M2Y4OGE0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzMjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MTdjZGI3MGIzMzNkZmY1N2FiYjM5MjIyZWQ0M2Q2M2FhNDU5ODZlM2RhOTFkYTg5ODA1NDUxZDdmMGIwNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H89bqyNKFAyt9FhqLnnW_j7_jsQ16kkUg24CJzLGNAM)

You can try my plugin bluetooth_print_plus, https://pub.dev/packages/bluetooth_print_plus

**Comment by AmanBhangre** [comment]
I am facing the same issue. Did you find any resolution?

**Comment by amoLink** [comment]
I have written a new plugin called bluetooth_print_plus,&nbsp;which may be helpful to you. You can try it out
link:&nbsp;https://pub.dev/packages/bluetooth_print_plus




amoLink
***@***.***



&nbsp;

**Comment by jsy11** [comment]
> I am facing the same issue. Did you find any resolution?

no... same. hopefully the contributors can address this issue soon.

**Comment by AmanBhangre** [comment]
> > I am facing the same issue. Did you find any resolution?
> 
> no... same. hopefully the contributors can address this issue soon.

I finally found the solution. Basically the package was not supporting the Bluetooth version of my printing device which is V2. I found this flutter blue plus package which worked really well with V2 devices.

**Comment by jsy11** [comment]
flutter blue plus package ? can you share the url? I can't find this.

**Comment by AmanBhangre** [comment]
> flutter blue plus package ? can you share the url? I can't find this.

Here it is : https://pub.dev/packages/flutter_blue_plus

**Comment by jsy11** [comment]
> > > I am facing the same issue. Did you find any resolution?
> > 
> > 
> > no... same. hopefully the contributors can address this issue soon.
> 
> I finally found the solution. Basically the package was not supporting the Bluetooth version of my printing device which is V2. I found this flutter blue plus package which worked really well with V2 devices.

Thanks! will explore this.

**Comment by jsy11** [comment]
The library you recommend not supported in printing as they dnt support Bluetooth classic and printer uses Bluetooth classic not BLE. "❗ Bluetooth Classic is not supported ❗ i.e. Arduino HC-05 & HC-06, speakers, headphones, mice, keyboards, gamepads, and more are not supported. These all use Bluetooth Classic. Also, iBeacons are not supported on iOS. Apple requires you to use CoreLocation.
