### ISSUE TITLE
device not showing

### ISSUE THREAD

**Issue by dev147jainsoft** [thon-ju/bluetooth_print#194]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method state on channel bluetooth_print/methods)
E/flutter ( 2768): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter ( 2768): <asynchronous suspension>
E/flutter ( 2768): #1      BluetoothPrint.state.<anonymous closure> (package:bluetooth_print/bluetooth_print.dart:54:53)
E/flutter ( 2768): <asynchronous suspension>
E/flutter ( 2768): #2      BluetoothPrint.state (package:bluetooth_print/bluetooth_print.dart:54:11)
E/flutter ( 2768): <asynchronous suspension>
E/flutter ( 2768): #3      _PrintTestState._startScan.<anonymous closure> (package:ssrcourier/screens/print_test.dart:41:33)
E/flutter ( 2768): <asynchronous suspension>
E/flutter ( 2768): 

this error i am getting

**Comment by amoLink** [comment]
You can give it a try：https://pub.dev/packages/bluetooth_print_plus

**Comment by krunalagrawal** [comment]
I have also faced this issue, try enabling the location service.
