### ISSUE TITLE
Scan doesn't work in Android 10

### ISSUE THREAD

**Issue by chiuhol** [thon-ju/bluetooth_print#43]

**Comment by DenisMrGnusa** [comment]
1. Same issue here, I've tried scan bluetooth device in android 10 device (Redmi Note 9 : Bluetooth version is 5.0), but callback give me nothing.
2. and I've tried in android 9 device (Realme C2 : Bluetooth version is 5.0), while scanning for devices managed to get a list of devices including the printer. but I can't connect to the printer I want and it shows up in a terminal like this.

```
D/BluetoothSocket(28482): close() this: android.bluetooth.BluetoothSocket@1a1c51a, channel: 2, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@80b084b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@e3b9228mSocket: null, mSocketState: CLOSED
D/BluetoothSocket(28482): close() this: android.bluetooth.BluetoothSocket@1a1c51a, channel: 2, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@80b084b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@e3b9228mSocket: null, mSocketState: CLOSED
W/System.err(28482): java.io.IOException: bt socket closed, read return: -1
W/System.err(28482): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:558)
W/System.err(28482): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:88)
W/System.err(28482): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err(28482): 	at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err(28482): 	at com.example.bluetooth_print.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:416)
W/System.err(28482): 	at com.example.bluetooth_print.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:496)
E/BluetoothPort(28482): connection device is lost
E/DeviceConnFactoryManager(28482):  read 0
D/BluetoothPrintPlugin(28482): stateStreamHandler, current action: android.bluetooth.device.action.ACL_DISCONNECTED
I/flutter (28482): cur device status: 0
```

*Printer
XPrinter BP-428U

**Comment by thantsin4ung** [comment]
Yeah I have same issues but build gradle compile sdk 28 and targetSDKversion 28 still work. My phone is android 10.
`compileSdkVersion 28`
`targetSdkVersion 28`

**Comment by imamabdulazis** [comment]
Is there any other solution?

**Comment by thon-ju** [comment]
please test latest version
