### ISSUE TITLE
Scanning bluetooth devices give me empty list (Android 10).

### ISSUE THREAD

**Issue by DenisMrGnusa** [thon-ju/bluetooth_print#47]
I tried this package with 2 devices,

Device 1. Same issue here, I've tried scan bluetooth device in android 10 device (Redmi Note 9 : Bluetooth version is 5.0), but callback give me nothing.

Device 2. and I've tried in android 9 device (Realme C2 : Bluetooth version is 5.0), while scanning for devices managed to get a list of devices including the printer. but I can't connect to the printer I want and it shows up in a terminal like this.

```
D/BluetoothSocket(28482): close() this: android.bluetooth.BluetoothSocket@1a1c51a, channel: 2, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@80b084b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@e3b9228mSocket: null, mSocketState: CLOSED
D/BluetoothSocket(28482): close() this: android.bluetooth.BluetoothSocket@1a1c51a, channel: 2, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@80b084b, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@e3b9228mSocket: null, mSocketState: CLOSED
W/System.err(28482): java.io.IOException: bt socket closed, read return: -1
W/System.err(28482): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:558)
W/System.err(28482): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:88)
W/System.err(28482): 	at java.io.InputStream.read(InputStream.java:101)
W/System.err(28482): 	at com.gprinter.io.BluetoothPort.readData(BluetoothPort.java:130)
W/System.err(28482): 	at com.example.bluetooth_print.DeviceConnFactoryManager.readDataImmediately(DeviceConnFactoryManager.java:416)
W/System.err(28482): 	at com.example.bluetooth_print.DeviceConnFactoryManager$PrinterReader.run(DeviceConnFactoryManager.java:496)
E/BluetoothPort(28482): connection device is lost
E/DeviceConnFactoryManager(28482):  read 0
D/BluetoothPrintPlugin(28482): stateStreamHandler, current action: android.bluetooth.device.action.ACL_DISCONNECTED
I/flutter (28482): cur device status: 0
```

*Printer
XPrinter BP-428U

**Comment by Yonkokilasi** [comment]
I'm facing the exact same issue on the same phone. Any solution for this ?

**Comment by thon-ju** [comment]
@DenisMrGnusa please test this project https://github.com/pauldemarco/flutter_blue?then tell me, if have the same problem

**Comment by Gibrat-Erisov** [comment]
I add these permissions to AndroidManifest.xml and it worked.

`<uses-permission android:name="android.permission.BLUETOOTH" />  
	 <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />  
	 <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/> `

**Comment by vborbely** [comment]
I had to enable Location on my phone to sense the devices.
I hope this helps.

**Comment by FabioPaganoAPSystem** [comment]
Yes @vborbely , in my case enabling location on the device solved the problem. Anyway I've seen that other packages don't need this setting. Thank you.

**Comment by vborbely** [comment]
> Yes @vborbely , in my case enabling location on the device solved the problem. Anyway I've seen that other packages don't need this setting. Thank you.

Great! Happy that it helped.
